name: cocinajusta
favicon: null
layout_spectrum: 0.89211
typography_spectrum: 0
title: Cocina Justa
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76341476-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c1ab93'
    - '#16110f'
    - '#ffffff'
    - '#ffff00'
    - '#326e8c'
  brandStrength: 0.0625
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
