name: cocinajusta
favicon: null
layout_spectrum: 0.99038
typography_spectrum: 0.7410538450349122
title: Cocina Justa
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#442a13'
    - '#6c8136'
    - '#cc6a29'
    - '#5dc7d2'
  brandStrength: 0
  lightness: 0.8844224619679153
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
